pipeline {
  agent {
    node {
      label any
    }
  }

  triggers {
    pollSCM 'H 20 * * 1-5'
  }

  stages {
    stage('checkout') {
      steps {
        checkout scm: [$class: 'GitSCM',
          userRemoteConfigs: [[url: 'git@github.com:dimaromantest/jenkins-pipeline-example.git',
                              credentialsId: 'myCredId']],
                              branches: [[name: 'refs/heads/master']]
        ], poll: true
      }
    }
  }
    post {
        failure {
            sh """
                curl -X POST -H "content-type: application/json" \
                -d '{"routing_key":"4ed6452f04494706d032708b605b8d90","event_action":"trigger","payload":{"summary":"${env.JOB_NAME} job failed ${env.BUILD_URL}","source":"Jenkins","severity":"critical","component":"exploratory-stats","group":"prod-datapipe","class":"deploy"}}' \
                https://events.pagerduty.com/v2/enqueue
                """
        }
    }  
}