node{

  git branch: "master", url: "https://github.com/dimaromantest/jenkins-pipeline-example" 

  stage('npm install') {

        sh "npm install"
  }

  stage ('npm test') {

        sh "npm test"

  }

        stage('Start Application'){
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "pankaj"
            }
            steps {
                sh 'npm start'
            }
        }

  stage ('Deploy app in DSV') {
    sh "docker rm -f app-dsv &>/dev/null && sleep 1 && docker run --name=app-dsv -p 8081:8081 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=dsv -d localhost:5000/jenkins-pipeline-example:dsv"
  }
  
}